[build]
  publish = "docs/build"
  command = "yarn install && ./scripts/netlify.sh"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[dev]
  targetPort = 3000
  port = 8888
  framework = "#custom"
  autoLaunch = true

[context.deploy-preview.environment]
  DEBUG = "netlify-plugin-cypress,netlify-plugin-cypress:verbose"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  # Cypress plugin will test our site after it is built
  package = "netlify-plugin-cypress"
    [plugins.inputs]
    record = true
