[build]
  publish = "docs/out"
  command = "./scripts/netlify.sh"

[dev]
  targetPort = 3000
  port = 8888
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
